In [1]:
import pandas as pd

In [2]:
# loading the dataset
df = pd.read_csv('./dataset/dirty_cafe_sales.csv')

df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [3]:
# Having a brief overview of range index, data types and any missikng values of the datatset using .info().
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [4]:
# havng a statistical summary of the dataset using .describe() function
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_9226047,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [5]:
# determining the dimension of the data in our dataset
df.shape

(10000, 8)

# Insight from our brief overview of our dataset using .info(), .describe() and .shape
- We can tell our dataset has 10,000 rows with the help of .info() and .shape, which also reveal that it has 8 columns.
- Additionally, .info() shows that most columns have missing values based on their non-null counts. Additionally, the output indicates that all columns are currently stored as object types, requiring us to convert several of them to numeric formats for modeling or analysis.

<!--  -->

In [6]:
# Create a copy of your dataset
df_copy = df.copy()

df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

## Column standardization

In [7]:
# Standardazing column names - remove extra spaces, before and after, lower case the column namw and replace spaces with underscores

df_copy.columns
df_copy.columns = df_copy.columns.str.strip().str.lower().str.replace(' ', '_', regex=False)

df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9862 non-null   object
 3   price_per_unit    9821 non-null   object
 4   total_spent       9827 non-null   object
 5   payment_method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

### Removing duplicates

In [8]:
# first check for duplicates
df_copy.duplicated().sum() # returns the sum of duplicates in the dataset

np.int64(0)

In [9]:
# drop duplicates
df_copy.drop_duplicates(inplace=True)

df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9862 non-null   object
 3   price_per_unit    9821 non-null   object
 4   total_spent       9827 non-null   object
 5   payment_method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

### Correcting data types

In [10]:
df_copy.head(10)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [11]:
# convert numeric columns - quantity, price_per_unit and total_spent, to numeric datatype

for col in ['quantity', 'price_per_unit', 'total_spent']:
    df_copy[col] = pd.to_numeric(df_copy[col], errors='coerce')

In [12]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   item              9667 non-null   object
 2   quantity          9521 non-null   float64
 3   price_per_unit    9467 non-null   float64
 4   total_spent       9498 non-null   float64
 5   payment_method    7421 non-null   object
 6   location          6735 non-null   object
 7   transaction_date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

### Handling missing Values

In [ ]:
# have a quick review of count of missing values per column
df_copy.isnull().sum()

transaction_id         0
item                 333
quantity             479
price_per_unit       533
total_spent          502
payment_method      2579
location            3265
transaction_date     159
dtype: int64

In [15]:
# imputate the missing values with a specific value or statistical measures like mean, median or mode of the column

# impute quantity and price_per unit column missing valuse using median
quantity_median = df_copy['quantity'].median()
price_median = df_copy['price_per_unit'].median()

print(quantity_median, price_median)

df_copy['quantity'].fillna(quantity_median, inplace=True)
df_copy['price_per_unit'].fillna(price_median, inplace=True)

# impute total_spent column missing values using quantity column value multiplied by price_per_unit column value
df_copy['total_spent'].fillna(df_copy['quantity'] * df_copy['price_per_unit'], inplace=True)

# verify if there is any missing values in the imputed columns
df_copy.isnull().sum()

3.0 3.0

/tmp/ipykernel_25240/83921641.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_copy['quantity'].fillna(quantity_median, inplace=True)
/tmp/ipykernel_25240/83921641.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_copy['price_per_unit'].fillna(price_median, inplace=True)
/tmp/ipykernel_25240/83921641.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_copy['total_spent'].fillna(df_copy['quantity'] * df_copy['price_per_unit'], inplace=True)

transaction_id         0
item                 333
quantity               0
price_per_unit         0
total_spent            0
payment_method      2579
location            3265
transaction_date     159
dtype: int64

In [17]:
df_copy.isnull().sum()

transaction_id         0
item                 333
quantity               0
price_per_unit         0
total_spent            0
payment_method      2579
location            3265
transaction_date     159
dtype: int64